language: rust
rust: stable

cache: cargo

env: MDBOOK=0.3.7 GHP_UPLOAD=0.3.4

install:
    - (test -x $HOME/.cargo/bin/mdbook || cargo install --version $MDBOOK mdbook)
    - (test -x $HOME/.cargo/bin/cargo-ghp-upload || cargo install --version $GHP_UPLOAD cargo-ghp-upload)

before_script:
    - rm -rf target

script:
    - mdbook build && touch book/.nojekyll && cargo ghp-upload --directory book -vvvv
